package studio.geonlee.auto_creator.common.enumeration;

/**
 * @author GEON
 * @since 2025-04-26
 **/
public enum CodeType {
    ENTITY,
    RECORD_CREATE_REQUEST,
    RECORD_CREATE_RESPONSE,
    RECORD_UPDATE_REQUEST,
    RECORD_UPDATE_RESPONSE,
    RECORD_DELETE_REQUEST,
    RECORD_DELETE_RESPONSE,
    RECORD_SEARCH_REQUEST,
    RECORD_SEARCH_RESPONSE,

    CONTROLLER,
    SERVICE_INTERFACE,
    SERVICE_IMPL,
    REPOSITORY,
    MAPSTRUCT_MAPPER,
    MAPPER,
    XML
}
